### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Ecksters** [iNightfaller/SpeedGuidesLive#1]
Can you share the source code for this project?

We're interested in it since it appears to be the only existing component that has dynamic per-split options,  and we're trying to create a similar functionality in a new Component.

**Comment by iNightfaller** [comment]
As of right now I'm actively making changes to the project and wish to continue making additions to the project. I have a backlog of bugs and features which I wish to manage myself, for experience, and to provide me with personal enjoyment. 

With that being said, if you have questions as to how I do something, I would be more than happy to provide you with snippets and/or pseudo code. 

I'm not too sure what you mean when you state you're looking for "dynamic per-split options." My interpretation of that is you're hoping to have things happen when the player splits? If that is the case, there's a set of events you can listen for which give you this ability. "LiveSplitState::OnSplit" is an example event, which is fired every time the user splits forward.

I hope this helps, and if you have any questions at all, feel free to ask! Many thanks!

**Comment by Ecksters** [comment]
Basically, we're hoping to avoid reinventing the wheel when it comes to the interface you have for adding notes to each split. In our case, we want to be able to call API endpoints or run script files specific to each split.

**Comment by iNightfaller** [comment]
I'm trying to get a better understanding as to what you're trying to attempt here. Are you trying to do something directly with guides, or are you trying to create something which doesn't have to do with the guides? After that, my questions are:
- are you just looking for logic to go from one split to another? 
- are you looking for something where individual splits do different things?
- anything else I should know?

**Comment by Ecksters** [comment]
Nothing directly with the guides, just that as far as I know, your Component is the only one that generates a form with options for each unique split, and saves those options.

In our case, we want to be able to run a different script for each split, rather than keeping notes for each split, we want to be able to store the path to the script.

**Comment by iNightfaller** [comment]
Okay, I believe I understand. When I am off work, I will write up some code for what you're looking for. Fortunately achieving what you want isn't too difficult, so I wouldn't mind writing up a derivative of my system, which wouldn't have the guide bloat.

**Comment by Ecksters** [comment]
Awesome, thank you so much!

**Comment by iNightfaller** [comment]
[LiveSplit.SplitHandlerTemplate.zip](https://github.com/iNightfaller/SpeedGuidesLive/files/1219354/LiveSplit.SplitHandlerTemplate.zip)

Here is a "template" of sorts you can use and reference yourself. The only thing I left out is the actual saving method for runs, IE: putting the run data into the data class. I hope this helps, and if you have any questions, feel free to ask.

**Comment by Ecksters** [comment]
Thanks a ton man, I'll post here when we finish our Component.
